= Notes
:toc:

General notes/toolchain tips.

== Installing Verilator

The quick way is to install from the package manager:

[,bash]
----
sudo apt install verilator
----

However, currently (on Ubuntu 22.04) this provides Verilator 4. If you need verilator 5, follow these steps to install it (see https://verilator.org/guide/latest/install.html[here]):

[,bash]
----
sudo apt remove verilator

sudo apt install git help2man perl python3 make autoconf g++ \
     flex bison ccache libgoogle-perftools-dev numactl perl-doc \
     libfl2 libfl-dev
----

Then clone the repository and build as follows:

[,bash]
----
git clone https://github.com/verilator/verilator
cd verilator

unset VERILATOR_ROOT
git checkout stable

# Install in your home directory to manage
# the installation more easily.
mkdir -p $HOME/opt

autoconf
./configure --prefix=$HOME/opt
make -j `nproc`
make install
----

Finally, make sure `$HOME/opt/bin` is added to your path in `.bashrc` (add `export PATH=$HOME/opt:$PATH`). Open a new terminal and run `verilator --version` to check the installation.

== Installing Verible

Verible provides binary releases for Linux https://github.com/chipsalliance/verible/releases[here]. Download the `.tar.gz` file for your architecture, and unzip it as follows:

[,bash]
----
cd $HOME/opt

# Replace to match your version
tar xvf ~/Downloads/verible-v0.0-3716-g914652db-linux-static-x86_64.tar.gz

# Create a symlink to the folder to make it
# easy to change version in future
ln -s verible-v0.0-3716-g914652db/ verible
----

Make sure `$HOME/opt/verible/bin` is added to your path in `.bashrc`. To check it works, open a new terminal and run `verible-verilog-lint --version`.

== Installing UVM

The Universal verification methodology (UVM) library is freely available from https://www.accellera.org/downloads/standards/uvm[here]. Download the `tar.gz` for the latest version (e.g. `UVM v2020.3.0 Library Code for IEEE 1800.2`), and extract it to any location:

[,bash]
----
cd $HOME/opt

tar xvf ~/Downloads/UVM-1900.2-2020.3.0.tar.gz
----

All that is required to use UVM is to point the simulation tools to the UVM directory.

== Installing UHDM
